export * from './articulo'
export * from './electronico'
export * from './abarrotes'
export * from './lg'
export * from './samsung'
export * from './ford'
export * from './chevrolet'
export * from './auto'